source 'https://rubygems.org'

gem 'jekyll'
gem 'sass'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
gem 'jekyll-coffeescript'
gem 'json'
